"""init schema

Revision ID: 888a6685f76f
Revises: 
Create Date: 2026-07-10 21:06:07.366127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '888a6685f76f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('messages',
    sa.Column('msg_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('receiver_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_index('idx_receiver_read', 'messages', ['receiver_id', 'is_read'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('reputation_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_email', 'users', ['email'], unique=False)
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('original_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('condition', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('images', sa.String(length=1000), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('idx_status_time', 'items', ['status', 'created_at'], unique=False)
    op.create_index('idx_status_time_cover', 'items', ['status', 'created_at', 'title', 'price'], unique=False)
    op.create_index('idx_user_id', 'items', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('favorite_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('favorite_id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item')
    )
    op.create_index('idx_favorite_user', 'favorites', ['user_id'], unique=False)
    op.create_table('requests',
    sa.Column('request_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('requester_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('idx_item_status', 'requests', ['item_id', 'status'], unique=False)
    op.create_index('idx_requester', 'requests', ['requester_id'], unique=False)
    op.create_index('idx_seller', 'requests', ['seller_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewee_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index('idx_request_id', 'reviews', ['request_id'], unique=False)
    op.create_index('idx_reviewee', 'reviews', ['reviewee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviewee', table_name='reviews')
    op.drop_index('idx_request_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_seller', table_name='requests')
    op.drop_index('idx_requester', table_name='requests')
    op.drop_index('idx_item_status', table_name='requests')
    op.drop_table('requests')
    op.drop_index('idx_favorite_user', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('idx_user_id', table_name='items')
    op.drop_index('idx_status_time_cover', table_name='items')
    op.drop_index('idx_status_time', table_name='items')
    op.drop_table('items')
    op.drop_index('idx_username', table_name='users')
    op.drop_index('idx_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_receiver_read', table_name='messages')
    op.drop_table('messages')
    op.drop_table('categories')
    # ### end Alembic commands ###
